matches:
    - trigger: ":a"
      replace: "{{output}}"
      vars:
          - name: "prompt"
            type: "form"
            params:
                layout: "What would you like to translate?\n\n[[text]]"
                fields:
                    text:
                        multiline: true
          - name: "output"
            type: "script"
            params:
                args:
                    - python
                    - "%CONFIG%/match/packages/espanso-llm-quick-translate/ask-ai.py"
                    - "{{prompt.text}}"
